name: Matrix functionality
on:
    push:
        branches:
            - master
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-versions: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include:
                    - node-versions: 18
                      operating-system: ubuntu-latest
                exclude:
                    - node-versions: 12
                      operating-system: windows-latest

        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install node JS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-versions }}
            - name: Install dependencies
              run: npm ci
            - name: Build Projects
              run: npm run build
