name: Reusable-deployment-file
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: echo "Reusable Deployment Func"